name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service:
          - name: frontend
            context: ./src/frontend
            dockerfile: ./src/frontend/Dockerfile
          - name: productcatalogservice
            context: ./src/productcatalogservice
            dockerfile: ./src/productcatalogservice/Dockerfile
          - name: cartservice
            context: ./src/cartservice/src               # <-- контекст теперь сама папка src
            dockerfile: ./src/cartservice/src/Dockerfile  # <-- путь к Dockerfile внутри неё
          - name: currencyservice
            context: ./src/currencyservice
            dockerfile: ./src/currencyservice/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert owner to lowercase
        id: lower
        run: |
          echo "owner_lc=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4   # обновлено до v4 (Node 24)
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6   # обновлено до v6 (Node 24)
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ steps.lower.outputs.owner_lc }}/${{ matrix.service.name }}:latest
            ghcr.io/${{ steps.lower.outputs.owner_lc }}/${{ matrix.service.name }}:${{ github.sha }}